# Generated by Django 2.2 on 2019-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
