# Generated by Django 2.2 on 2019-08-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190814_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='order_status',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
