# Generated by Django 2.2 on 2019-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='order_status',
            field=models.CharField(default='', max_length=80),
        ),
    ]
