# Generated by Django 2.2 on 2019-08-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190817_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='table',
            field=models.IntegerField(default=0),
        ),
    ]
