# Generated by Django 2.2 on 2019-08-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190826_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='انتخاب غذا', max_length=80),
        ),
    ]
