# Generated by Django 2.2 on 2019-08-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=40)),
                ('rest_banner', models.TextField()),
                ('rest_logo', models.ImageField(default='../media/foodImages/default.jpg', upload_to='foodImages/')),
                ('bg_picture', models.ImageField(default='../media/foodImages/default.jpg', upload_to='foodImages/')),
            ],
        ),
    ]
