# Generated by Django 2.2 on 2019-08-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='options',
            name='rest_logo',
        ),
        migrations.AlterField(
            model_name='options',
            name='bg_picture',
            field=models.ImageField(default='../media/optionsImages/default.jpg', upload_to='optionsImages/'),
        ),
    ]
