# Generated by Django 2.2 on 2019-08-08 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_food', models.IntegerField(default=0)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='omega_app.Food')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(to='omega_app.Product'),
        ),
    ]
