# Generated by Django 2.2 on 2019-08-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0004_auto_20190808_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food',
            new_name='product',
        ),
    ]
