# Generated by Django 2.2 on 2019-08-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0005_auto_20190808_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
