# Generated by Django 2.2 on 2019-08-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0006_order_customer_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omega_app.Food'),
        ),
    ]
