# Generated by Django 2.2 on 2019-08-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0007_auto_20190808_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='show_admin',
            field=models.BooleanField(default=False),
        ),
    ]
