# Generated by Django 2.2 on 2019-08-19 15:38

from django.db import migrations, models
import jdatetime


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0008_order_show_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='food',
            name='added_date',
            field=models.DateTimeField(default=jdatetime.datetime.now),
        ),
    ]
