# Generated by Django 2.2 on 2019-08-21 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0009_auto_20190819_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='preparing_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='registration_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
