# Generated by Django 2.2 on 2019-08-21 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0010_auto_20190821_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
