# Generated by Django 2.2 on 2019-08-26 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0012_auto_20190823_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='added_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
