# Generated by Django 2.2 on 2019-08-26 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0013_auto_20190826_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
