# Generated by Django 2.2 on 2019-08-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0015_food_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='destination',
            field=models.CharField(default='True', max_length=10),
        ),
    ]
