# Generated by Django 2.2 on 2019-09-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omega_app', '0016_auto_20190827_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm_services',
            field=models.BooleanField(default=False),
        ),
    ]
